name: Half-year calendar

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate half-year calendar
      - name: Generate half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: calendar.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes

      # Generate basic profile
      - name: Generate basic profile
        uses: lowlighter/metrics@latest
        with:
          filename: basicprofile.plugin.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Bogota
          plugin_introduction: yes
          plugin_introduction_title: yes
         
      # Generate repositories
      - name: Pinned repositories
        uses: lowlighter/metrics@latest
        with:
          filename: repositories.pinned.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_repositories: yes
          plugin_repositories_featured: sistema-gestion-inventarios, hoja_de_vida
          plugin_repositories_order: featured, pinned, starred, random
          plugin_repositories_pinned: 6
          plugin_repositories_affiliations: owner, collaborator, organization_member      

      # Generate full-year calendar with language analysis
      - name: Generate lenguage
        uses: lowlighter/metrics@latest
        with:
          filename: lenguage.plugin.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_sections: recently-used, most-used
          plugin_languages_colors: github
          plugin_languages_limit: 8

        
