name: lenguages

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Lenguages 
        uses: lowlighter/metrics@latest
        with:
          filename: lenguages.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_colors: rainbow
          plugin_languages_limit: 6
          plugin_languages_analysis_timeout: 15
      
